<a href="https://colab.research.google.com/github/as183789043/PyTorch-for-Deep-Learning-in-2023-Zero-to-Mastery/blob/main/00Pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Udemy Pytorch 環境快速開始設定



In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch

In [2]:
print(torch.__version__)

2.1.0+cu121


In [3]:
!nvidia-smi

Fri Dec 22 13:04:24 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Introduction Tensor
create Pytorch Tensor using function => `torch.tensor()`

In [4]:
#scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [5]:
# get ndim
print(scalar.ndim)

0


In [6]:
#get tensor back as pytohn  int
scalar.item()


7

In [7]:
# if i want create a vector
vector = torch.tensor([7,7])
print(vector)

tensor([7, 7])


In [8]:
# get ndim
vector.ndim

1

In [9]:
# create matrix
matrix = torch.tensor([
    [7,7],
    [8,8]]
)
matrix


tensor([[7, 7],
        [8, 8]])

In [10]:
#grt metrix ndim and shape and size
matrix.ndim


2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
matrix[0]

tensor([7, 7])

In [13]:
# tenosr
tensor = torch.tensor([[[1,2,3],
            [3.,6,9],
            [2,4,5]]])
tensor

tensor([[[1., 2., 3.],
         [3., 6., 9.],
         [2., 4., 5.]]])

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

torch.Size([1, 3, 3])

## Random Tensor

In [16]:
## Random Tensor
## Why random tensor ?
'''Random tensor are important because the way many neural networks learn is that they start with tensor  furll of random nunbers and then adjust those random random numbers to etter represent the data'''

'Random tensor are important because the way many neural networks learn is that they start with tensor  furll of random nunbers and then adjust those random random numbers to etter represent the data'

`start with random numbers -> look at data -> update random numbers -> look at data -> update random nunbers`

In [17]:
# create a random tensor of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7235, 0.4450, 0.8545, 0.1503],
        [0.7956, 0.9622, 0.5098, 0.5281],
        [0.1024, 0.5982, 0.8715, 0.0576]])

In [18]:
random_tensor.ndim

2

In [19]:
# create a random tensor with simliar shape to an image tensor
random_image_size_tensor=torch.rand(size=(3,244,244,)) #height,width,colur channel
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

### Zero And Ones

In [20]:
# create a tensor of all ones
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
## create a tensor of ones
ones = torch.ones(size=(5,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [23]:
# use torch.arage()
one_to_ten=torch.arange(start=0,end=10,step=1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# create  tensor like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes
**Note** Tensor Big Question of 3
- Tensor not right dtype
- Tensor not right shape
- Tensor not on  right device

In [25]:
# Float 32
float_16_tensor = torch.tensor([3.0,6.0,9.0],
                dtype=torch.float16,
                device="cuda",
                requires_grad=False)
float_16_tensor.dtype

torch.float16

In [26]:
## Convert dtype
float_32_tensor = float_16_tensor.type(torch.float32)
float_32_tensor.dtype
float_32_tensor.device

device(type='cuda', index=0)

## Get information for tensor
- Tensor not right dtype  `<tensor.name>.dtyep`
- Tensor not right shape  `<tensor.name>.shape`
- Tensor not on  right device `<tensor.name>.device``

In [27]:
##　create a rand tenssor
rand_tensor = torch.rand(size=(3,255,255))
rand_tensor

tensor([[[0.3769, 0.1472, 0.7762,  ..., 0.2292, 0.7984, 0.5126],
         [0.4954, 0.5300, 0.9317,  ..., 0.8319, 0.7293, 0.7786],
         [0.7675, 0.0772, 0.2136,  ..., 0.3407, 0.5140, 0.5744],
         ...,
         [0.6300, 0.2745, 0.5838,  ..., 0.6043, 0.7532, 0.5433],
         [0.6920, 0.1127, 0.7104,  ..., 0.3576, 0.3381, 0.9376],
         [0.0817, 0.8179, 0.1036,  ..., 0.7188, 0.6295, 0.0549]],

        [[0.2471, 0.8939, 0.6899,  ..., 0.8407, 0.9295, 0.3270],
         [0.4110, 0.7039, 0.5622,  ..., 0.7360, 0.4743, 0.0882],
         [0.9849, 0.7828, 0.9966,  ..., 0.4087, 0.9250, 0.4457],
         ...,
         [0.3859, 0.1161, 0.2158,  ..., 0.4703, 0.7826, 0.8613],
         [0.2855, 0.9003, 0.0455,  ..., 0.6448, 0.6993, 0.6707],
         [0.9682, 0.2216, 0.4013,  ..., 0.6369, 0.2575, 0.8512]],

        [[0.8122, 0.4710, 0.0537,  ..., 0.6321, 0.3144, 0.0384],
         [0.8408, 0.3508, 0.7377,  ..., 0.5738, 0.5247, 0.6898],
         [0.5031, 0.2880, 0.2762,  ..., 0.0034, 0.4219, 0.

In [28]:
## Find out detail
print(f"rand_tensor_shape:  {tensor.shape}")
print(f"rand_tensor_dtype:  {tensor.dtype}")
print(f"rand_tensor_device:  {tensor.device}")

rand_tensor_shape:  torch.Size([1, 3, 3])
rand_tensor_dtype:  torch.float32
rand_tensor_device:  cpu


## Manipulation Tensors (tensor operations)
Teensor operations includes:
- addition
- subscration
- multiplication (eement-wise)
- division
- matirx multiplication

In [29]:
## create a tensor to multiplication
tesor_a =torch.tensor([1,2,3])
print(tesor_a * tesor_a)   # 1*1 + 2*2 +3*3


tensor([1, 4, 9])


In [36]:
## creaqte a tensor
tensor = torch.tensor([1,2,3])
tensor +10

tensor([11, 12, 13])

In [37]:
tensor * 10

tensor([10, 20, 30])

In [38]:
tensor / 2

tensor([0.5000, 1.0000, 1.5000])

In [39]:
tensor -10

tensor([-9, -8, -7])

In [40]:
#＃　use pytroch function
tensor.mul(2)

tensor([2, 4, 6])

## matirx multiplication (dot product)
### there are two rule performing matirx multiplication neesd to satisfy:
1. The **inner dim** Must math
- `(3,2)@*(3,2)` not work
- `(3,2)@*(2,3)`  work
- `(2,3)@*(3,2)`  work
2. The result Matrix has the shape of the **outer dim**:
- `(2,3)@(3,2)` -> `(2.2)`
- `(3,2)@(2,3)` -> `(3.3)`


In [41]:
test_torch = torch.rand(3,2)
test_torch@test_torch   ## @ =matirx multiplication

RuntimeError: ignored

In [42]:
torch.matmul(test_torch,test_torch)

RuntimeError: ignored

In [43]:
work_torch = torch.ones(2,3)
torch.matmul(test_torch,work_torch)

tensor([[0.7759, 0.7759, 0.7759],
        [0.3535, 0.3535, 0.3535],
        [1.1449, 1.1449, 1.1449]])

## One of the most commom errors in deep learning: shape errors

In [44]:
#　Sapes for matrix multiplication
tensor_A = torch.tensor([
    [1,2],
    [3,4],
    [5,6]
                         ])
tensor_B = torch.tensor([
    [7,10],
    [8,11],
    [9,12]
                         ])

torch.mm(tensor_A,tensor_B)  ## torch.mm == torch.malmul() alias


RuntimeError: ignored

 TO fix our tensor shape issues , we can mainpulate the shape f one of our tesors using **transpose**

In [45]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [46]:
tensor_B.T.shape

torch.Size([2, 3])

In [47]:
torch.mm(tensor_A,tensor_B.T)   #(3,2) @(2,3) **inner dim** match

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## find the min,mx ,mean ,sum,etc (tensor aggreation))

In [48]:
# create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [49]:
#　min
torch.min(x) ,x.min()

(tensor(0), tensor(0))

In [50]:
# max
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [51]:
torch.mean(x)

RuntimeError: ignored

In [ ]:
x.dtype

In [52]:
## change type to use mean function
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [53]:
## find the sum
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

## find the poistion min and max

In [54]:
# find the position in tensor tat has th emin value with argmin()-> returns index poistion of target  tensor whrere rhe min value occurs
x= torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [55]:
x[1]

tensor(10)

In [56]:
x.argmin()

tensor(0)

In [57]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing, and unsqueezing tensors
- Reshaping -> reshapes an input tensor to a defined shape
- View   -> Returrn a vuew of an input tensor of certain shape but keep the same meory as the origin tensor
- Stacking -> combine multiple tenosor on top of each other or side by sideby side  (hstack)
- squeeze -> remoce all `1` dimension from a tensor
- unsqueeze -> add a `1` dimension to  a target  tensor
- Permute -> Return a view of the input with dimensions prtmuted(swapped) in a certain way


In [58]:
#　create a tensor
import torch
x=torch.arange(1.,10.)
x,x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [59]:
#　add an extra dimension
x_reshaped= x.reshape(3,3)
x_reshaped


tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [60]:
# chage the view
z =x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [61]:
# change z to x (beacuse a view of a tensor shares the same memory as the original input)
z[0,:] =5
z,x

(tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5.]]),
 tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.]))

In [62]:
## stack  tensor on top of each other
x_stacked = torch.stack([x,x,x,x,x],dim=2)
x_stacked


IndexError: ignored

In [63]:
x_stacked = torch.stack([x,x,x,x,x],dim=0)   # stach tensor 依照 dim排序
x_stacked


tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [64]:
# torch.sueeze() ＃　降維  remove all single dimension from a target tensor
print(f"previous: {z}")
print(f"previous_shape: {z.shape}")
print(f"after: {torch.squeeze(z)}")
print(f"after_shape: {torch.squeeze(z).shape}")


previous: tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5.]])
previous_shape: torch.Size([1, 9])
after: tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.])
after_shape: torch.Size([9])


In [65]:
#　torch.unsqueeze() add a single dimension to a target tensor at a specific dim
tensor_un = torch.rand(size=(3,4))
tensor_un


tensor([[0.2951, 0.6972, 0.9517, 0.9162],
        [0.1136, 0.6039, 0.4521, 0.0025],
        [0.6767, 0.0893, 0.5257, 0.1506]])

In [66]:
unsqueeze = torch.squeeze(tensor_un)
unsqueeze.shape

torch.Size([3, 4])

In [67]:
unsqueeze.unsqueeze(dim=0),unsqueeze.unsqueeze(dim=0).shape

(tensor([[[0.2951, 0.6972, 0.9517, 0.9162],
          [0.1136, 0.6039, 0.4521, 0.0025],
          [0.6767, 0.0893, 0.5257, 0.1506]]]),
 torch.Size([1, 3, 4]))

In [68]:
unsqueeze.unsqueeze(dim=1),unsqueeze.unsqueeze(dim=1).shape

(tensor([[[0.2951, 0.6972, 0.9517, 0.9162]],
 
         [[0.1136, 0.6039, 0.4521, 0.0025]],
 
         [[0.6767, 0.0893, 0.5257, 0.1506]]]),
 torch.Size([3, 1, 4]))

In [69]:
unsqueeze.unsqueeze(dim=2),unsqueeze.unsqueeze(dim=2).shape

(tensor([[[0.2951],
          [0.6972],
          [0.9517],
          [0.9162]],
 
         [[0.1136],
          [0.6039],
          [0.4521],
          [0.0025]],
 
         [[0.6767],
          [0.0893],
          [0.5257],
          [0.1506]]]),
 torch.Size([3, 4, 1]))

## torch.permute - rearranges the dimension of atagett tensor in a specific order

In [70]:
x = torch.rand(2,3,5)
x

tensor([[[0.4750, 0.8096, 0.1109, 0.1164, 0.6975],
         [0.6905, 0.3625, 0.8577, 0.4302, 0.4543],
         [0.6913, 0.4439, 0.5767, 0.4443, 0.0316]],

        [[0.1689, 0.3098, 0.8306, 0.2205, 0.2940],
         [0.6938, 0.2311, 0.5892, 0.0502, 0.6441],
         [0.9823, 0.7702, 0.7723, 0.6938, 0.7296]]])

In [71]:
x.size()

torch.Size([2, 3, 5])

In [72]:
torch.permute(x,(2,0,1)).size() #shift axis 0->1,1->2,2->0

torch.Size([5, 2, 3])

In [73]:
torch.permute(x,(2,0,1)).shape

torch.Size([5, 2, 3])

Indexing (selecting data from tensors)
indexing with pytorch is similar to indexing with Numpy


In [74]:
# create s tensor
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [75]:
# let index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [76]:
# index on our tensor (dim=1 )
x[0,0],x[0][0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [77]:
#　let index on the most inner bracket (last dimension)
x[0,0,1]

tensor(2)

In [78]:
#　you can also use : to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [79]:
#　get all values of 0th and 1st dmension but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [80]:
# get all values of the 0 dim but only 1 index value of 1 st and 2nd dim
x[:,:,1]

tensor([[2, 5, 8]])

In [81]:
#　get index 0 of 0th and 1st dim all values of 2nd dim
x[0,0,:]

tensor([1, 2, 3])

In [82]:
#　index on x to  return 9
print(x[0,2,2])
#　return 3,6,9
print(x[:,:,2])


tensor(9)
tensor([[3, 6, 9]])


## Pytorch tensor & Numpy
Numpy is a popular sciebtic Pytho numercial computing library
And because og this,Pytorch  has functionality to interact with it .
- Data is Numpy , want is Pytorch tensor -> `torch.from_numpy(ndarray)`
- Pytorch tensor -> Numpy -> `torch.tensor.numpy()`

In [83]:
#　Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) #　warning: when convert from numpy -> pytorch,torch reflects numpy's default datatype of float64 unless specified otherwise
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [84]:
#　change the value of array,what will this do to ``tensor
array.dtype

dtype('float64')

In [85]:
array=array+1
array

array([2., 3., 4., 5., 6., 7., 8.])

In [86]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [87]:
# change the tensor ,what happens to `numpy_tensor`?
tensor = tensor +1
tensor


tensor([2., 2., 2., 2., 2., 2., 2.])

## Reproducbility(trying to take random out of random)
in short how a neural networks learns:
`start with random numbers -> tensor operationd -> update random numbers
 to try and make them of the data -> again -> again-> again ...`

 To reduce the randomness in neural networks and Pytorch comes the concept of a `random seed`.
  
 Essentially what the random seed does is "flavour" the randomness

In [88]:
torch.rand(3,3)

tensor([[0.8970, 0.0023, 0.4085],
        [0.9178, 0.2139, 0.5205],
        [0.7732, 0.7566, 0.1504]])

In [89]:
import torch
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.5843, 0.6130, 0.5382, 0.3975],
        [0.3350, 0.5562, 0.0929, 0.8201],
        [0.4948, 0.2562, 0.3231, 0.3285]])
tensor([[0.2891, 0.2995, 0.8337, 0.2475],
        [0.7157, 0.7858, 0.1866, 0.6250],
        [0.1417, 0.9223, 0.3451, 0.6676]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [90]:
#  let make some random ut reproducible tensors
import torch
#　set the random seed  #random seed 調用一次ran後需重新指定
random_seed =42
torch.manual_seed(random_seed)
random_tensor_C =torch.rand(3,4)

torch.manual_seed(random_seed)
random_tensor_D =torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch object on the GPUs (and making faster computations)

GPU =  Faster computation on numbers ,thanks to CUDA + NVDIA handware + PyTorch working behind the scenes to make everything hunky dory(good)

In [91]:
##　Running tensors and Pytorch object on the GPUs (and making faster computations)

## Getting a GPU
#1. Use google.colab
#2. use your ownn
#3. use cloud computing - GCP,AWS,Azure


In [92]:
#　xheck for GPU acces with Pytorch
import torch
torch.cuda.is_available()

True

In [93]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [94]:
# count number of  devices
torch.cuda.device_count()

1


#3. Ptting tensors (and models) on the GPU
the reason we want our tensor/models on the GPU is beacauswe using a GPU results in faster computaations

In [95]:
#  create a tensor (defaulrs on the cpu)
tensor = torch.tensor([1,2,3])

# tensor not on gpu
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [96]:
# tensor  on gpu
tensor_on_GPU = tensor.to(device)
tensor_on_GPU

tensor([1, 2, 3], device='cuda:0')

4. Moving tensors back to the GPU


In [97]:
#４．if tensor is on GPU, can't tranform it  to numpy
tensor_on_GPU.numpy()

TypeError: ignored

In [98]:
#　TO fix the GPU tensor with Numpy issue ,we canm fitst set it to the gpu
tensor_on_GPU.cpu()

tensor([1, 2, 3])

In [99]:
tensor_on_GPU.cpu().numpy()

array([1, 2, 3])